Repository mezzio/mezzio-problem-details, pull requests merged in 2022-02, with the labels that each got.

#23 Reference RFC 7807 in `README` and `composer.json`
  README.md
  composer.json
Labels: Documentation, Enhancement

#25 Synchronize `site_description` with `composer` and github repository description
  mkdocs.yml
Labels: Documentation

#27 Prepare for Renovate with reusable workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  composer.json
  composer.lock
  psalm-baseline.xml
Labels: Enhancement
